import { Inter } from 'next/font/google'
import '../css/plugins.css';
import '../css/style.css';
import '../css/templete.css';
import '../css/skin/skin-1.css';
import '../plugins/slick/slick.min.css';
import '../plugins/slick/slick-theme.min.css';

import Header from '../markup/Layout/Header';
import Footer from '../markup/Layout/Footer';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'HireLab',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
